class Constants:

    COMMENT_REGEX = r"\/\*[\s\S]*?\*\/|\/\/.*"
    COMMENT_TYPE = "COMMENT"
    DOCSTRING_REGEX = r"\/\*\*[\s\S]*?\*\/|\/\/\/"
    DOCSTRING_TYPE = "DOCSTRING"
    DUMMY_REGEX = r"\(|{|}|,|="
    DUMMY_TYPE = "DUMMY"
    END_TYPE = "END"
    END_KEYWORD = "end"
    FLOAT_REGEX = r"-?\d+?\.\d+(e\d+)?"
    FLOAT_TYPE = "FLOAT"
    FUNCTION_KEYWORD = "fn"
    FUNCTION_NAME = "function"
    FUNCTION_TERMINATOR_REGEX = r"\)"
    FUNCTION_TERMINATOR_TYPE = "FUNCTION_TERMINATOR"
    FUNCTION_TYPE = "FUNCTION"
    IDENTIFIER_REGEX = r"[\w:]+"
    IDENTIFIER_TYPE = "IDENTIFIER"
    INTEGER_REGEX = r"-?\d+(e\d+)?"
    INTEGER_TYPE = "INTEGER"
    JUMP_KEYWORD = "jmp"
    JUMP_TYPE = "JUMP"
    LINE_TERMINATOR = ";"
    LINE_TERMINATOR_TYPE = "LINE_TERMINATOR"
    MAIN_KEYWORD = "mn"
    MAIN_NAME = "main"
    MAIN_TYPE = "MAIN"
    OUT_KEYWORD = "out"
    OUT_TYPE = "OUT"
    RAW_SET_KEYWORD = "rset"
    RAW_SET_TYPE = "RAW_SET"
    REFERENCE_OPERATOR = "::"
    SET_KEYWORD = "set"
    SET_TYPE = "SET"
    SHEBANG_REGEX = r"#!.*\n"
    SHEBANG_TYPE = "SHEBANG"
    START_KEYWORD = "start"
    START_TYPE = "START"
    STOP_KEYWORD = "stop"
    STOP_TYPE = "STOP"
    STRING_REGEX = r"\"(?:[^\"]*)\""
    STRING_TYPE = "STRING"
    UNMAPPED_REGEX = "."
    UNMAPPED_TYPE = "UNMAPPED"
    WHITESPACE_REGEX = r"[\s]+"
    WHITESPACE_TYPE = "WHITESPACE"

    @staticmethod
    def reference(variable: str):

        return variable + Constants.REFERENCE_OPERATOR
